from .models import SourceClass

SOURCES = {
    "govuk": {
        "id": "govuk",
        "authority": "UK Foreign, Commonwealth & Development Office",
        "source_class": SourceClass.GOVERNMENT_ADVISORY.value,
        "jurisdiction": "destination",
        "machine_readable": True,
        "refresh": "6h",
        "official": True,
        "mvp": True,
        "url": "https://www.gov.uk/foreign-travel-advice",
        "notes": "Structured foreign-travel-advice. Advisory, not destination primary law.",
    },
    "iso-reference": {
        "id": "iso-reference",
        "authority": "ISO 3166 / ISO 4217 reference table",
        "source_class": SourceClass.REFERENCE_DATA.value,
        "jurisdiction": "GLOBAL",
        "machine_readable": True,
        "refresh": "manual",
        "official": True,
        "mvp": True,
        "url": "https://www.iso.org/iso-3166-country-codes.html",
        "notes": "Bundled ISO country/currency/language/driving-side metadata only.",
    },
    "worldbank": {
        "id": "worldbank",
        "authority": "World Bank country API",
        "source_class": SourceClass.REFERENCE_DATA.value,
        "jurisdiction": "GLOBAL",
        "machine_readable": True,
        "refresh": "weekly",
        "official": True,
        "mvp": True,
        "url": "https://api.worldbank.org/v2/country",
        "notes": "Capital and region metadata. Not law.",
    },
    "frankfurter": {
        "id": "frankfurter",
        "authority": "Frankfurter FX",
        "source_class": SourceClass.REFERENCE_DATA.value,
        "jurisdiction": "GLOBAL",
        "machine_readable": True,
        "refresh": "daily",
        "official": False,
        "mvp": True,
        "url": "https://api.frankfurter.app",
        "notes": "Reference FX rates, not a legal or payment instruction.",
    },
    "gdacs": {
        "id": "gdacs",
        "authority": "Global Disaster Alert and Coordination System",
        "source_class": SourceClass.INTERGOVERNMENTAL_ALERT.value,
        "jurisdiction": "GLOBAL",
        "machine_readable": True,
        "refresh": "15m",
        "official": True,
        "mvp": True,
        "url": "https://www.gdacs.org",
        "notes": "Disaster alerts. Never presented as destination law.",
    },
    "reliefweb": {
        "id": "reliefweb",
        "authority": "UN OCHA ReliefWeb",
        "source_class": SourceClass.INTERGOVERNMENTAL_ALERT.value,
        "jurisdiction": "GLOBAL",
        "machine_readable": True,
        "refresh": "1h",
        "official": True,
        "mvp": True,
        "url": "https://reliefweb.int",
        "notes": "Humanitarian/disruption context. Never presented as destination law.",
    },
    "state_dept": {
        "id": "state_dept",
        "authority": "U.S. Department of State",
        "source_class": SourceClass.GOVERNMENT_ADVISORY.value,
        "jurisdiction": "US-traveler",
        "machine_readable": "rss/pages",
        "refresh": "1h",
        "official": True,
        "mvp": False,
        "url": "https://travel.state.gov",
        "notes": "Listed for later U.S.-traveler context. Not ingested in this MVP.",
    },
}
