export const COUNTRIES: { iso2: string; name: string }[] = [
  { iso2: 'US', name: 'United States' },
  { iso2: 'GB', name: 'United Kingdom' },
  { iso2: 'CA', name: 'Canada' },
  { iso2: 'AU', name: 'Australia' },
  { iso2: 'NZ', name: 'New Zealand' },
  { iso2: 'IE', name: 'Ireland' },
  { iso2: 'DE', name: 'Germany' },
  { iso2: 'FR', name: 'France' },
  { iso2: 'ES', name: 'Spain' },
  { iso2: 'IT', name: 'Italy' },
  { iso2: 'NL', name: 'Netherlands' },
  { iso2: 'SE', name: 'Sweden' },
  { iso2: 'NO', name: 'Norway' },
  { iso2: 'DK', name: 'Denmark' },
  { iso2: 'JP', name: 'Japan' },
  { iso2: 'KR', name: 'South Korea' },
  { iso2: 'CN', name: 'China' },
  { iso2: 'IN', name: 'India' },
  { iso2: 'MX', name: 'Mexico' },
  { iso2: 'BR', name: 'Brazil' },
  { iso2: 'AR', name: 'Argentina' },
  { iso2: 'ZA', name: 'South Africa' },
  { iso2: 'NG', name: 'Nigeria' },
  { iso2: 'KE', name: 'Kenya' },
  { iso2: 'EG', name: 'Egypt' },
  { iso2: 'AE', name: 'United Arab Emirates' },
  { iso2: 'SA', name: 'Saudi Arabia' },
  { iso2: 'TR', name: 'Turkey' },
  { iso2: 'TH', name: 'Thailand' },
  { iso2: 'VN', name: 'Vietnam' },
  { iso2: 'PH', name: 'Philippines' },
  { iso2: 'ID', name: 'Indonesia' },
  { iso2: 'MY', name: 'Malaysia' },
  { iso2: 'SG', name: 'Singapore' },
  { iso2: 'MA', name: 'Morocco' },
  { iso2: 'PT', name: 'Portugal' },
  { iso2: 'PL', name: 'Poland' },
  { iso2: 'CH', name: 'Switzerland' },
  { iso2: 'AT', name: 'Austria' },
  { iso2: 'BE', name: 'Belgium' },
];

export function countryName(iso2: string | undefined): string {
  if (!iso2) return '';
  return COUNTRIES.find((item) => item.iso2 === iso2.toUpperCase())?.name ?? iso2;
}
